### ISSUE TITLE
Segment Integration | Trying to fetch keys from appboy.xml | Polluting stacktrace

### ISSUE THREAD

**Issue by HamzaIsrar12** [Appboy/appboy-segment-android#33]
Hello Team 👋 

I'm using Appboy with Segment integration. This is my appboy configuration implementation in the main application: 

```
    AppboyConfig appboyConfig = new AppboyConfig.Builder()
        .setIsFirebaseCloudMessagingRegistrationEnabled(true)
        .setFirebaseCloudMessagingSenderIdKey(firebaseConfig.projectNumber)
        .setHandlePushDeepLinksAutomatically(true)
        .build();
    Appboy.configure(this, appboyConfig);
    registerActivityLifecycleCallbacks(new AppboyLifecycleCallbackListener(true, true));
```

I'm using the library version 7.0.0: `com.appboy:appboy-segment-integration:7.0.0`

### Scenario:
For the pre-login experience, I'm seeing a high number of error logs in stacktrace generated by Appboy. It's trying to fetch the API keys from `res/values/appboy.xml` which doesn't exist in my case since I'm the segment SDK fetches it for me. What could be the reason? 🤔 

Ps: It's not a crash but I'm seeing a `Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again` exception on crashlytics for one or two users. I hope it's not related to this. 💥 

### Stacktrace:

My stacktrace is filled with them. I have only pasted a few of them. 🗑️ 

```
I/Appboy v10.0.0 .com.appboy.Appboy: Appboy outbound network requests are now enabled
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: ****************************************************
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                                                **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                 !! WARNING !!                  **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                                                **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **     No API key set in res/values/appboy.xml    **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: ** No cached API Key found from Appboy.configure  **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **          Braze functionality disabled          **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                                                **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: ****************************************************
E/Appboy v10.0.0 .com.appboy.Appboy: Caught exception while retrieving API key.
    java.lang.RuntimeException: Unable to read the Braze API key from the res/values/appboy.xml file or from runtime configuration via AppboyConfig. See log for more details.
        at com.appboy.configuration.AppboyConfigurationProvider.getAppboyApiKey(SourceFile:35)
        at com.appboy.Appboy.getConfiguredApiKey(SourceFile:1)
        at com.appboy.Appboy.getInstance(SourceFile:6)
        at com.appboy.ui.inappmessage.AppboyInAppMessageManager.ensureSubscribedToInAppMessageEvents(AppboyInAppMessageManager.java:132)
        at com.appboy.AppboyLifecycleCallbackListener.onActivityCreated(AppboyLifecycleCallbackListener.java:153)
        at android.app.Application.dispatchActivityCreated(Application.java:375)
        at android.app.Activity.dispatchActivityCreated(Activity.java:1382)
        at android.app.Activity.onCreate(Activity.java:1655)
        at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:314)
        at org.edx.mobile.view.SplashActivity.onCreate(SplashActivity.java:30)
        at android.app.Activity.performCreate(Activity.java:8142)
        at android.app.Activity.performCreate(Activity.java:8114)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3549)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3748)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2187)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8057)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
        
I/Appboy v10.0.0 .com.appboy.Appboy: Firebase Cloud Messaging found. Setting up Firebase Cloud Messaging.
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: ****************************************************
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                                                **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                 !! WARNING !!                  **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                                                **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **     No API key set in res/values/appboy.xml    **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: ** No cached API Key found from Appboy.configure  **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **          Braze functionality disabled          **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                                                **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: ****************************************************
E/Appboy v10.0.0 .com.appboy.Appboy: Failed to startup user dependency manager.
    java.lang.RuntimeException: Unable to read the Braze API key from the res/values/appboy.xml file or from runtime configuration via AppboyConfig. See log for more details.
        at com.appboy.configuration.AppboyConfigurationProvider.getAppboyApiKey(SourceFile:35)
        at bo.app.q4.<init>(SourceFile:3)
        at com.appboy.Appboy.h(SourceFile:3)
        at com.appboy.Appboy.$r8$lambda$LNLRr-BQWVG2_sF6UwoY_xQi_vY(Unknown Source:0)
        at com.appboy.Appboy$$ExternalSyntheticLambda32.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
E/Appboy v10.0.0 .com.appboy.Appboy: Cannot publish error on null publisher. This is usually the result of a missing API key.
    java.lang.RuntimeException: Unable to read the Braze API key from the res/values/appboy.xml file or from runtime configuration via AppboyConfig. See log for more details.
        at com.appboy.configuration.AppboyConfigurationProvider.getAppboyApiKey(SourceFile:35)
        at bo.app.q4.<init>(SourceFile:3)
        at com.appboy.Appboy.h(SourceFile:3)
        at com.appboy.Appboy.$r8$lambda$LNLRr-BQWVG2_sF6UwoY_xQi_vY(Unknown Source:0)
        at com.appboy.Appboy$$ExternalSyntheticLambda32.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
        
I/Appboy v10.0.0 .com.appboy.Appboy: Appboy outbound network requests are now enabled
W/Appboy v10.0.0 .com.appboy.Appboy: API key not present. Not performing action on SDK.
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: ****************************************************
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                                                **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                 !! WARNING !!                  **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                                                **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **     No API key set in res/values/appboy.xml    **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: ** No cached API Key found from Appboy.configure  **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **          Braze functionality disabled          **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                                                **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: ****************************************************
E/Appboy v10.0.0 .com.appboy.Appboy: Caught exception while retrieving API key.
    java.lang.RuntimeException: Unable to read the Braze API key from the res/values/appboy.xml file or from runtime configuration via AppboyConfig. See log for more details.
        at com.appboy.configuration.AppboyConfigurationProvider.getAppboyApiKey(SourceFile:35)
        at com.appboy.Appboy.getConfiguredApiKey(SourceFile:1)
        at com.appboy.Appboy.getInstance(SourceFile:6)
        at com.appboy.AppboyLifecycleCallbackListener.onActivityStarted(AppboyLifecycleCallbackListener.java:121)
        at android.app.Application.dispatchActivityStarted(Application.java:408)
        at android.app.Activity.dispatchActivityStarted(Activity.java:1414)
        at android.app.Activity.onStart(Activity.java:1907)
        at org.edx.mobile.view.Hilt_SplashActivity.onStart(Unknown Source:0)
        at org.edx.mobile.view.SplashActivity.onStart(SplashActivity.java:58)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8173)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3602)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2187)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8057)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
        
W/Appboy v10.0.0 .com.appboy.Appboy: API key not present. Not performing action on SDK.
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: ****************************************************
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                                                **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                 !! WARNING !!                  **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                                                **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **     No API key set in res/values/appboy.xml    **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: ** No cached API Key found from Appboy.configure  **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **          Braze functionality disabled          **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: **                                                **
W/Appboy v10.0.0 .com.appboy.configuration.AppboyConfigurationProvider: ****************************************************
E/Appboy v10.0.0 .com.appboy.Appboy: Failed to startup user dependency manager.
    java.lang.RuntimeException: Unable to read the Braze API key from the res/values/appboy.xml file or from runtime configuration via AppboyConfig. See log for more details.
        at com.appboy.configuration.AppboyConfigurationProvider.getAppboyApiKey(SourceFile:35)
        at bo.app.q4.<init>(SourceFile:3)
        at com.appboy.Appboy.h(SourceFile:3)
        at com.appboy.Appboy.$r8$lambda$LNLRr-BQWVG2_sF6UwoY_xQi_vY(Unknown Source:0)
        at com.appboy.Appboy$$ExternalSyntheticLambda32.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
E/Appboy v10.0.0 .com.appboy.Appboy: Cannot publish error on null publisher. This is usually the result of a missing API key.
    java.lang.RuntimeException: Unable to read the Braze API key from the res/values/appboy.xml file or from runtime configuration via AppboyConfig. See log for more details.
        at com.appboy.configuration.AppboyConfigurationProvider.getAppboyApiKey(SourceFile:35)
        at bo.app.q4.<init>(SourceFile:3)
        at com.appboy.Appboy.h(SourceFile:3)
        at com.appboy.Appboy.$r8$lambda$LNLRr-BQWVG2_sF6UwoY_xQi_vY(Unknown Source:0)
        at com.appboy.Appboy$$ExternalSyntheticLambda32.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
I/Appboy v10.0.0 .com.appboy.Appboy: Firebase Cloud Messaging found. Setting up Firebase Cloud Messaging.

**Comment by Bucimis** [comment]
@HamzaIsrar12 Since the SDK needs to be dynamically initialized with an API key at runtime in the Segment/Braze integration, you actually shouldn't use `registerActivityLifecycleCallbacks()` at all. Doing so will set up lifecycle listeners that will inappropriately initialize the SDK automatically upon certain app lifecycle events. This isn't good because in the Segment/Braze integration, we can't safely initialize the SDK (which happens upon any call to `getInstance()` until Segment is able to configure the SDK with an API key at runtime.

The Segment codebase handles all the functionality normally included in `registerActivityLifecycleCallbacks()` automatically.

To configure your firebase integration, you can use a `braze.xml` or continue to call `configure()`

**Comment by HamzaIsrar12** [comment]
@Bucimis  Thanks, That worked like a charm. ✨
