### ISSUE TITLE
Segment analytics android 4.3.0 "No virtual method logCustomEvent" crash with appboy android-sdk-ui version >= 2.1

### ISSUE THREAD

**Issue by xanexpt** [Appboy/appboy-segment-android#4]
## Using these versions of the libraries, the app crashes 
    
compile 'com.segment.analytics.android:analytics:4.3.0'
compile 'com.appboy:android-sdk-ui:2.2.4'

# CrashLog:
after read 
* Analytics: Ran TrackPayload{event="Application Updated"} on integration Segment.io in 2630154 ns.
* Analytics-Appboy: Calling appboy.logCustomEvent for event Application Updated with properties {"version":"version-of-the-app","build":37,"previous_version":"previous.version-of-the-app","previous_build":36}.
* FATAL EXCEPTION: main
                                                                           Process: com.myapp.android.client.dev, PID: 9591
                                                                           java.lang.NoSuchMethodError: No virtual method logCustomEvent(Ljava/lang/String;Lcom/appboy/models/outgoing/AppboyProperties;)Z in class Lcom/appboy/Appboy; or its super classes (declaration of 'com.appboy.Appboy' appears in /data/app/com.myapp.android.client.dev-1/base.apk:classes32.dex)
                                                                               at com.segment.analytics.android.integrations.appboy.AppboyIntegration.track(AppboyIntegration.java:241)
                                                                               at com.segment.analytics.IntegrationOperation$10.run(IntegrationOperation.java:176)
                                                                               at com.segment.analytics.Analytics.performRun(Analytics.java:1463)
                                                                               at com.segment.analytics.Analytics$10.run(Analytics.java:824)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

I already tried some versions of com.appboy:android-sdk-ui, its currently working with 2.0.4, but if I change to 2.1.0 or another one more recent, it always crashes

**Comment by Bucimis** [comment]
Hi @xanexpt,

Thanks for contacting us. Our segment integration pulls down the correct version of the Braze Android SDK automatically (currently `2.2.1`).

Please remove the line `compile 'com.appboy:android-sdk-ui:2.2.4'` from your `build.gradle` and see if that resolves your issue.

Thanks,
Braze SDK Engineering

**Comment by xanexpt** [comment]
Hello,

It is working, 
The solution was to remove the line you said.

Thanks
