### ISSUE TITLE
NPE Crash in a activity that have the fragment AppboyFeedFragment()

### ISSUE THREAD

**Issue by xanexpt** [Appboy/appboy-segment-android#6]
Hello,

I'm using
com.appboy:appboy-segment-integration:2.1.1
com.zendesk:support:2.0.0

I had this crash, do you guys have any information about this?

It's in a screen where I have an Activity with AppboyFeedFragment() and implement IFeedClickActionListener

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.android/com.app.android.ui.FeedActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.concurrent.ThreadPoolExecutor.execute(java.lang.Runnable)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3003)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6816)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by Bucimis** [comment]
Hi @xanexpt,

Thanks for reporting this issue. How many users are experiencing the crash? Are you able to repro it? Does it happen upon activity entry, exit, or while interacting with the feed?

**Comment by xanexpt** [comment]
I'm not able to reproduce it yet. I only have the logs from the crash. 
Do you guys have logs when the SDK crashes that can show a more detailed stacktrace?

**Comment by Bucimis** [comment]
@xanexpt gotcha. You can enable verbose logging in the SDK to get a better sense of what the SDK was doing prior to a given crash, but thats less useful if you can't repro locally.

In general, the issue appears to be occurring before your custom `FeedActivity` activity is instantiated and there isn't evidence that this is a Braze SDK crash (i.e. Appboy code doesn't appear in the stacktrace).
